window.mockCards = [
  // 20 employer
  {
    role: "employer",
    name: "Марія К.",
    subtitle: "Няня, 32 роки",
    rating: 5,
    reviews: 24,
    experience: "5 років досвіду",
    experienceYears: 5,
    category: "nanny",
    location: "Київ, Оболонь",
    locationKey: "kyiv",
    schedule: "Повний день",
    scheduleType: "full-time",
    employmentType: "permanent",
    frequencyType: "daily",
    price: 200,
    badge: "Перевірено",
    img: "/api/placeholder/300/200",
    contacts: "Телефон: +380501234567, Viber",
    createdAt: "2025-05-14",
  },
  {
    role: "employer",
    name: "Ольга В.",
    subtitle: "Доглядальниця, 45 років",
    rating: 4,
    reviews: 18,
    experience: "8 років досвіду",
    experienceYears: 8,
    category: "caretaker",
    location: "Львів, Центр",
    locationKey: "lviv",
    schedule: "Гнучкий графік",
    scheduleType: "flexible",
    employmentType: "permanent",
    frequencyType: "daily",
    price: 180,
    badge: "Перевірено",
    img: "/api/placeholder/300/200",
    contacts: "Телефон: +380501234567, Viber",
    createdAt: "2025-05-14",
  },
  {
    role: "employer",
    name: "Іван П.",
    subtitle: "Домробітник, 40 років",
    rating: 5,
    reviews: 30,
    experience: "10 років досвіду",
    experienceYears: 10,
    category: "housekeeper",
    location: "Одеса, Приморський",
    locationKey: "odesa",
    schedule: "Неповний день",
    scheduleType: "part-time",
    employmentType: "permanent",
    frequencyType: "weekly",
    price: 220,
    badge: "Premium",
    img: "/api/placeholder/300/200",
    contacts: "Телефон: +380501234567, Viber",
    createdAt: "2025-05-14",
  },
  {
    role: "employer",
    name: "Світлана С.",
    subtitle: "Кухар, 29 років",
    rating: 4,
    reviews: 12,
    experience: "4 роки досвіду",
    experienceYears: 4,
    category: "cook",
    location: "Дніпро, Соборний",
    locationKey: "dnipro",
    schedule: "Повний день",
    scheduleType: "full-time",
    employmentType: "permanent",
    frequencyType: "daily",
    price: 250,
    badge: "Перевірено",
    img: "/api/placeholder/300/200",
    contacts: "Телефон: +380501234567, Viber",
    createdAt: "2025-05-14",
  },
  {
    role: "employer",
    name: "Петро Д.",
    subtitle: "Садівник, 50 років",
    rating: 5,
    reviews: 20,
    experience: "15 років досвіду",
    experienceYears: 15,
    category: "gardener",
    location: "Харків, Шевченківський",
    locationKey: "kharkiv",
    schedule: "Гнучкий графік",
    scheduleType: "flexible",
    employmentType: "permanent",
    frequencyType: "weekly",
    price: 210,
    badge: "Premium",
    img: "/api/placeholder/300/200",
    contacts: "Телефон: +380501234567, Viber",
    createdAt: "2025-05-14",
  },
  {
    role: "employer",
    name: "Анна Л.",
    subtitle: "Няня, 28 років",
    rating: 4,
    reviews: 10,
    experience: "3 роки досвіду",
    experienceYears: 3,
    category: "nanny",
    location: "Запоріжжя, Хортицький",
    locationKey: "zaporizhzhia",
    schedule: "Повний день",
    scheduleType: "full-time",
    employmentType: "permanent",
    frequencyType: "daily",
    price: 230,
    badge: "Терміново",
    img: "/api/placeholder/300/200",
    contacts: "Телефон: +380501234567, Viber",
    createdAt: "2025-05-14",
  },
  {
    role: "employer",
    name: "Віктор К.",
    subtitle: "Доглядальник, 38 років",
    rating: 5,
    reviews: 15,
    experience: "7 років досвіду",
    experienceYears: 7,
    category: "caretaker",
    location: "Вінниця, Замостя",
    locationKey: "vinnytsia",
    schedule: "Неповний день",
    scheduleType: "part-time",
    employmentType: "permanent",
    frequencyType: "weekly",
    price: 190,
    badge: "Перевірено",
    img: "/api/placeholder/300/200",
    contacts: "Телефон: +380501234567, Viber",
    createdAt: "2025-05-14",
  },
  {
    role: "employer",
    name: "Олена М.",
    subtitle: "Домробітниця, 35 років",
    rating: 4,
    reviews: 22,
    experience: "6 років досвіду",
    experienceYears: 6,
    category: "housekeeper",
    location: "Івано-Франківськ, Центр",
    locationKey: "ivano-frankivsk",
    schedule: "Повний день",
    scheduleType: "full-time",
    employmentType: "permanent",
    frequencyType: "daily",
    price: 240,
    badge: "Premium",
    img: "/api/placeholder/300/200",
    contacts: "Телефон: +380501234567, Viber",
    createdAt: "2025-05-14",
  },
  {
    role: "employer",
    name: "Дмитро Б.",
    subtitle: "Кухар, 41 рік",
    rating: 5,
    reviews: 19,
    experience: "12 років досвіду",
    experienceYears: 12,
    category: "cook",
    location: "Тернопіль, Новий Світ",
    locationKey: "ternopil",
    schedule: "Гнучкий графік",
    scheduleType: "flexible",
    employmentType: "temporary",
    frequencyType: "weekly",
    price: 260,
    badge: "Терміново",
    img: "/api/placeholder/300/200",
    contacts: "Телефон: +380501234567, Viber",
    createdAt: "2025-05-14",
  },
  {
    role: "employer",
    name: "Катерина Г.",
    subtitle: "Няня, 30 років",
    rating: 4,
    reviews: 14,
    experience: "5 років досвіду",
    experienceYears: 5,
    category: "nanny",
    location: "Київ, Шулявка",
    locationKey: "kyiv",
    schedule: "Повний день",
    scheduleType: "full-time",
    employmentType: "permanent",
    frequencyType: "daily",
    price: 210,
    badge: "Перевірено",
    img: "/api/placeholder/300/200",
    contacts: "Телефон: +380501234567, Viber",
    createdAt: "2025-05-14",
  },
  // 10 еще карточек employer
  {
    role: "employer",
    name: "Олександр Ж.",
    subtitle: "Садівник, 55 років",
    rating: 5,
    reviews: 25,
    experience: "20 років досвіду",
    experienceYears: 20,
    category: "gardener",
    location: "Житомир, Богунський",
    locationKey: "zhytomyr",
    schedule: "Гнучкий графік",
    scheduleType: "flexible",
    employmentType: "permanent",
    frequencyType: "weekly",
    price: 200,
    badge: "Premium",
    img: "/api/placeholder/300/200",
    contacts: "Телефон: +380501234567, Viber",
    createdAt: "2025-05-14",
  },
  {
    role: "employer",
    name: "Ірина З.",
    subtitle: "Домробітниця, 27 років",
    rating: 4,
    reviews: 11,
    experience: "2 роки досвіду",
    experienceYears: 2,
    category: "housekeeper",
    location: "Луцьк, 33-й квартал",
    locationKey: "lutsk",
    schedule: "Повний день",
    scheduleType: "full-time",
    employmentType: "permanent",
    frequencyType: "daily",
    price: 180,
    badge: "Терміново",
    img: "/api/placeholder/300/200",
    contacts: "Телефон: +380501234567, Viber",
    createdAt: "2025-05-14",
  },
  {
    role: "employer",
    name: "Валерій І.",
    subtitle: "Кухар, 36 років",
    rating: 5,
    reviews: 17,
    experience: "8 років досвіду",
    experienceYears: 8,
    category: "cook",
    location: "Чернівці, Садгора",
    locationKey: "chernivtsi",
    schedule: "Неповний день",
    scheduleType: "part-time",
    employmentType: "temporary",
    frequencyType: "weekly",
    price: 220,
    badge: "Перевірено",
    img: "/api/placeholder/300/200",
    contacts: "Телефон: +380501234567, Viber",
    createdAt: "2025-05-14",
  },
  {
    role: "employer",
    name: "Тетяна К.",
    subtitle: "Няня, 33 роки",
    rating: 4,
    reviews: 13,
    experience: "4 роки досвіду",
    experienceYears: 4,
    category: "nanny",
    location: "Хмельницький, Виставка",
    locationKey: "khmelnytskyi",
    schedule: "Повний день",
    scheduleType: "full-time",
    employmentType: "permanent",
    frequencyType: "daily",
    price: 230,
    badge: "Premium",
    img: "/api/placeholder/300/200",
    contacts: "Телефон: +380501234567, Viber",
    createdAt: "2025-05-14",
  },
  {
    role: "employer",
    name: "Ганна Л.",
    subtitle: "Доглядальниця, 48 років",
    rating: 5,
    reviews: 21,
    experience: "11 років досвіду",
    experienceYears: 11,
    category: "caretaker",
    location: "Черкаси, Митниця",
    locationKey: "cherkasy",
    schedule: "Гнучкий графік",
    scheduleType: "flexible",
    employmentType: "permanent",
    frequencyType: "weekly",
    price: 210,
    badge: "Перевірено",
    img: "/api/placeholder/300/200",
    contacts: "Телефон: +380501234567, Viber",
    createdAt: "2025-05-14",
  },
  {
    role: "employer",
    name: "Руслан М.",
    subtitle: "Домробітник, 39 років",
    rating: 4,
    reviews: 16,
    experience: "7 років досвіду",
    experienceYears: 7,
    category: "housekeeper",
    location: "Полтава, Подол",
    locationKey: "poltava",
    schedule: "Повний день",
    scheduleType: "full-time",
    employmentType: "permanent",
    frequencyType: "daily",
    price: 240,
    badge: "Терміново",
    img: "/api/placeholder/300/200",
    contacts: "Телефон: +380501234567, Viber",
    createdAt: "2025-05-14",
  },
  {
    role: "employer",
    name: "Людмила Н.",
    subtitle: "Кухар, 44 роки",
    rating: 5,
    reviews: 18,
    experience: "13 років досвіду",
    experienceYears: 13,
    category: "cook",
    location: "Рівне, Ювілейний",
    locationKey: "rivne",
    schedule: "Гнучкий графік",
    scheduleType: "flexible",
    employmentType: "temporary",
    frequencyType: "weekly",
    price: 260,
    badge: "Premium",
    img: "/api/placeholder/300/200",
    contacts: "Телефон: +380501234567, Viber",
    createdAt: "2025-05-14",
  },
  {
    role: "employer",
    name: "Євген О.",
    subtitle: "Садівник, 52 роки",
    rating: 4,
    reviews: 20,
    experience: "18 років досвіду",
    experienceYears: 18,
    category: "gardener",
    location: "Кривий Ріг, Саксаганський",
    locationKey: "kryvyi-rih",
    schedule: "Повний день",
    scheduleType: "full-time",
    employmentType: "permanent",
    frequencyType: "daily",
    price: 210,
    badge: "Перевірено",
    img: "/api/placeholder/300/200",
    contacts: "Телефон: +380501234567, Viber",
    createdAt: "2025-05-14",
  },
  {
    role: "employer",
    name: "Віра П.",
    subtitle: "Няня, 31 рік",
    rating: 5,
    reviews: 12,
    experience: "6 років досвіду",
    experienceYears: 6,
    category: "nanny",
    location: "Миколаїв, Соляні",
    locationKey: "mykolaiv",
    schedule: "Неповний день",
    scheduleType: "part-time",
    employmentType: "temporary",
    frequencyType: "weekly",
    price: 200,
    badge: "Терміново",
    img: "/api/placeholder/300/200",
    contacts: "Телефон: +380501234567, Viber",
    createdAt: "2025-05-14",
  },
  {
    role: "employer",
    name: "Максим Р.",
    subtitle: "Домробітник, 42 роки",
    rating: 4,
    reviews: 14,
    experience: "9 років досвіду",
    experienceYears: 9,
    category: "housekeeper",
    location: "Київ, Оболонь",
    locationKey: "kyiv",
    schedule: "Повний день",
    scheduleType: "full-time",
    employmentType: "permanent",
    frequencyType: "daily",
    price: 230,
    badge: "Перевірено",
    img: "/api/placeholder/300/200",
    contacts: "Телефон: +380501234567, Viber",
    createdAt: "2025-05-14",
  },

  // 20 worker
  {
    role: "worker",
    title: "Догляд за дитиною",
    subtitle: "Потрібна няня для дитини 3 років",
    category: "nanny",
    location: "Одеса, Аркадія",
    locationKey: "odesa",
    schedule: "Повний день",
    scheduleType: "full-time",
    employment: "Постійна робота",
    employmentType: "permanent",
    frequency: "Щодня",
    frequencyType: "daily",
    price: 250,
    badge: "Терміново",
    createdAt: "2025-05-14",
    description: "Потрібна няня для дитини 3 років. Обов'язки: догляд, прогулянки, приготування їжі для дитини, розвиток за віком.",
    requirements: "Досвід роботи з дітьми від 2 років, відповідальність, охайність, без шкідливих звичок.",
    contacts: "Телефон: +380501234567, Viber",
    bonus: "Оплачувані лікарняні, премії за гарну роботу.",
  },
  {
    role: "worker",
    title: "Прибирання квартири",
    subtitle: "Потрібна домробітниця для щотижневого прибирання",
    category: "housekeeper",
    location: "Львів, Сихів",
    locationKey: "lviv",
    schedule: "Гнучкий графік",
    scheduleType: "flexible",
    employment: "Тимчасова робота",
    employmentType: "temporary",
    frequency: "Щотижня",
    frequencyType: "weekly",
    price: 220,
    badge: "Premium",
    createdAt: "2025-05-13",
    description: "Щотижневе прибирання 3-кімнатної квартири. Миття підлоги, вікон, санвузла, прасування білизни.",
    requirements: "Досвід роботи від 1 року, акуратність, пунктуальність.",
    contacts: "Телефон: +380631112233",
    bonus: "Чайові, гнучкий графік.",
  },
  {
    role: "worker",
    title: "Догляд за літньою людиною",
    subtitle: "Потрібна доглядальниця для бабусі",
    category: "caretaker",
    location: "Дніпро, Тополя",
    locationKey: "dnipro",
    schedule: "Повний день",
    scheduleType: "full-time",
    employment: "Постійна робота",
    employmentType: "permanent",
    frequency: "Щодня",
    frequencyType: "daily",
    price: 260,
    badge: "Перевірено",
    createdAt: "2025-05-12",
    description: "Догляд за бабусею 82 років: допомога у пересуванні, контроль прийому ліків, приготування їжі.",
    requirements: "Медична освіта вітається, досвід роботи з літніми людьми.",
    contacts: "Телефон: +380971234567",
    bonus: "Безкоштовне харчування, проживання.",
  },
  {
    role: "worker",
    title: "Садівник",
    subtitle: "Догляд за садом та газоном",
    category: "gardener",
    location: "Київ, Солом’янка",
    locationKey: "kyiv",
    schedule: "Неповний день",
    scheduleType: "part-time",
    employment: "Сезонна робота",
    employmentType: "seasonal",
    frequency: "2 рази на тиждень",
    frequencyType: "weekly",
    price: 200,
    badge: "Новинка",
    createdAt: "2025-05-11",
    description: "Догляд за рослинами, стрижка газону, полив, підживлення.",
    requirements: "Знання садових рослин, досвід роботи від 1 року.",
    contacts: "Телефон: +380991234567",
    bonus: "Безкоштовні обіди.",
  },
  {
    role: "worker",
    title: "Кухар",
    subtitle: "Потрібен кухар для сім’ї",
    category: "cook",
    location: "Харків, Олексіївка",
    locationKey: "kharkiv",
    schedule: "Повний день",
    scheduleType: "full-time",
    employment: "Постійна робота",
    employmentType: "permanent",
    frequency: "Щодня",
    frequencyType: "daily",
    price: 300,
    badge: "Терміново",
    createdAt: "2025-05-10",
    description: "Приготування домашньої їжі для сім’ї з 4 осіб, складання меню.",
    requirements: "Досвід роботи кухарем від 2 років, охайність.",
    contacts: "Телефон: +380661234567",
    bonus: "Премії, харчування за рахунок роботодавця.",
  },
  {
    role: "worker",
    title: "Репетитор англійської",
    subtitle: "Підготовка до ЗНО",
    category: "tutor",
    location: "Київ, Позняки",
    locationKey: "kyiv",
    schedule: "Гнучкий графік",
    scheduleType: "flexible",
    employment: "Підробіток",
    employmentType: "part-time",
    frequency: "2-3 рази на тиждень",
    frequencyType: "weekly",
    price: 350,
    badge: "Premium",
    createdAt: "2025-05-09",
    description: "Підготовка учнів до ЗНО з англійської мови, індивідуальні заняття.",
    requirements: "Вища освіта, досвід викладання від 3 років.",
    contacts: "Телефон: +380501112233",
    bonus: "Гнучкий графік, навчальні матеріали.",
  },
  {
    role: "worker",
    title: "Водій",
    subtitle: "Сімейний водій",
    category: "driver",
    location: "Львів, Центр",
    locationKey: "lviv",
    schedule: "Повний день",
    scheduleType: "full-time",
    employment: "Постійна робота",
    employmentType: "permanent",
    frequency: "Щодня",
    frequencyType: "daily",
    price: 400,
    badge: "Перевірено",
    createdAt: "2025-05-08",
    description: "Перевезення членів сім’ї, виконання доручень, догляд за авто.",
    requirements: "Водійські права категорії B, досвід від 5 років.",
    contacts: "Телефон: +380931234567",
    bonus: "Оплата пального, бонуси за безаварійну їзду.",
  },
  {
    role: "worker",
    title: "Догляд за тваринами",
    subtitle: "Вигул собак",
    category: "pets",
    location: "Київ, Оболонь",
    locationKey: "kyiv",
    schedule: "Гнучкий графік",
    scheduleType: "flexible",
    employment: "Підробіток",
    employmentType: "part-time",
    frequency: "Щодня",
    frequencyType: "daily",
    price: 150,
    badge: "Новинка",
    createdAt: "2025-05-07",
    description: "Вигул собак різних порід, догляд за тваринами під час відпустки власників.",
    requirements: "Любов до тварин, досвід роботи з собаками.",
    contacts: "Телефон: +380671234567",
    bonus: "Гнучкий графік, бонуси за постійних клієнтів.",
  },
  {
    role: "worker",
    title: "Майстер на годину",
    subtitle: "Дрібний ремонт по дому",
    category: "handyman",
    location: "Дніпро, Центр",
    locationKey: "dnipro",
    schedule: "Гнучкий графік",
    scheduleType: "flexible",
    employment: "Підробіток",
    employmentType: "part-time",
    frequency: "За потребою",
    frequencyType: "on-demand",
    price: 250,
    badge: "Терміново",
    createdAt: "2025-05-06",
    description: "Виконання дрібних ремонтних робіт: сантехніка, електрика, меблі.",
    requirements: "Досвід роботи, власний інструмент.",
    contacts: "Телефон: +380991112233",
    bonus: "Оплата за кожне замовлення.",
  },
  {
    role: "worker",
    title: "Покоївка",
    subtitle: "Прибирання готельних номерів",
    category: "housekeeper",
    location: "Одеса, Центр",
    locationKey: "odesa",
    schedule: "Позмінно",
    scheduleType: "shift",
    employment: "Тимчасова робота",
    employmentType: "temporary",
    frequency: "Щодня",
    frequencyType: "daily",
    price: 180,
    badge: "Premium",
    createdAt: "2025-05-05",
    description: "Прибирання номерів у готелі, зміна постільної білизни, підтримка чистоти.",
    requirements: "Охайність, відповідальність.",
    contacts: "Телефон: +380681234567",
    bonus: "Чайові, харчування.",
  },
  {
    role: "worker",
    title: "Сиділка",
    subtitle: "Догляд за хворим",
    category: "caretaker",
    location: "Харків, Салтівка",
    locationKey: "kharkiv",
    schedule: "Повний день",
    scheduleType: "full-time",
    employment: "Постійна робота",
    employmentType: "permanent",
    frequency: "Щодня",
    frequencyType: "daily",
    price: 270,
    badge: "Терміново",
    createdAt: "2025-05-04",
    description: "Догляд за лежачим хворим, контроль прийому ліків, гігієнічні процедури.",
    requirements: "Досвід роботи, медична освіта вітається.",
    contacts: "Телефон: +380951234567",
    bonus: "Проживання, харчування.",
  },
  {
    role: "worker",
    title: "Гувернантка",
    subtitle: "Розвиток та навчання дітей",
    category: "nanny",
    location: "Київ, Печерськ",
    locationKey: "kyiv",
    schedule: "Гнучкий графік",
    scheduleType: "flexible",
    employment: "Постійна робота",
    employmentType: "permanent",
    frequency: "Щодня",
    frequencyType: "daily",
    price: 320,
    badge: "Premium",
    createdAt: "2025-05-03",
    description: "Розвиток, навчання, організація дозвілля для дітей 5-8 років.",
    requirements: "Педагогічна освіта, досвід роботи з дітьми.",
    contacts: "Телефон: +380991234568",
    bonus: "Навчальні матеріали, премії.",
  },
  {
    role: "worker",
    title: "Посудомийка",
    subtitle: "Робота в ресторані",
    category: "kitchen",
    location: "Львів, Франківський",
    locationKey: "lviv",
    schedule: "Позмінно",
    scheduleType: "shift",
    employment: "Тимчасова робота",
    employmentType: "temporary",
    frequency: "Щодня",
    frequencyType: "daily",
    price: 160,
    badge: "Новинка",
    createdAt: "2025-05-02",
    description: "Миття посуду, прибирання кухні, допомога кухарям.",
    requirements: "Охайність, відповідальність.",
    contacts: "Телефон: +380671234568",
    bonus: "Харчування, чайові.",
  },
  {
    role: "worker",
    title: "Садівник",
    subtitle: "Догляд за квітами та деревами",
    category: "gardener",
    location: "Дніпро, Перемога",
    locationKey: "dnipro",
    schedule: "Гнучкий графік",
    scheduleType: "flexible",
    employment: "Сезонна робота",
    employmentType: "seasonal",
    frequency: "3 рази на тиждень",
    frequencyType: "weekly",
    price: 210,
    badge: "Перевірено",
    createdAt: "2025-05-01",
    description: "Посадка, полив, обрізка дерев та кущів, догляд за квітами.",
    requirements: "Досвід роботи з рослинами.",
    contacts: "Телефон: +380991234569",
    bonus: "Безкоштовні обіди.",
  },
  {
    role: "worker",
    title: "Пральня",
    subtitle: "Прання та прасування білизни",
    category: "laundry",
    location: "Київ, Лівобережна",
    locationKey: "kyiv",
    schedule: "Позмінно",
    scheduleType: "shift",
    employment: "Тимчасова робота",
    employmentType: "temporary",
    frequency: "Щодня",
    frequencyType: "daily",
    price: 170,
    badge: "Новинка",
    createdAt: "2025-04-30",
    description: "Прання, прасування, складання білизни для готелю.",
    requirements: "Охайність, уважність.",
    contacts: "Телефон: +380991234570",
    bonus: "Харчування, премії.",
  },
  {
    role: "worker",
    title: "Догляд за дітьми",
    subtitle: "Няня для двійнят",
    category: "nanny",
    location: "Харків, Центр",
    locationKey: "kharkiv",
    schedule: "Повний день",
    scheduleType: "full-time",
    employment: "Постійна робота",
    employmentType: "permanent",
    frequency: "Щодня",
    frequencyType: "daily",
    price: 350,
    badge: "Premium",
    createdAt: "2025-04-29",
    description: "Догляд за двома дітьми 2 років, організація ігор, прогулянки.",
    requirements: "Досвід роботи з малюками, рекомендації.",
    contacts: "Телефон: +380991234571",
    bonus: "Премії, харчування.",
  },
  {
    role: "worker",
    title: "Догляд за тваринами",
    subtitle: "Догляд за котами під час відпустки",
    category: "pets",
    location: "Львів, Личаківський",
    locationKey: "lviv",
    schedule: "Гнучкий графік",
    scheduleType: "flexible",
    employment: "Підробіток",
    employmentType: "part-time",
    frequency: "За потребою",
    frequencyType: "on-demand",
    price: 120,
    badge: "Новинка",
    createdAt: "2025-04-28",
    description: "Годування, прибирання лотка, ігри з котами.",
    requirements: "Любов до тварин, акуратність.",
    contacts: "Телефон: +380991234572",
    bonus: "Гнучкий графік.",
  },
  {
    role: "worker",
    title: "Репетитор математики",
    subtitle: "Підготовка до ДПА",
    category: "tutor",
    location: "Київ, Виноградар",
    locationKey: "kyiv",
    schedule: "Гнучкий графік",
    scheduleType: "flexible",
    employment: "Підробіток",
    employmentType: "part-time",
    frequency: "2 рази на тиждень",
    frequencyType: "weekly",
    price: 300,
    badge: "Premium",
    createdAt: "2025-04-27",
    description: "Підготовка учнів 9 класу до ДПА з математики.",
    requirements: "Вища освіта, досвід викладання.",
    contacts: "Телефон: +380991234573",
    bonus: "Навчальні матеріали.",
  },
  {
    role: "worker",
    title: "Майстер з ремонту",
    subtitle: "Ремонт побутової техніки",
    category: "handyman",
    location: "Дніпро, Лівий берег",
    locationKey: "dnipro",
    schedule: "Гнучкий графік",
    scheduleType: "flexible",
    employment: "Підробіток",
    employmentType: "part-time",
    frequency: "За потребою",
    frequencyType: "on-demand",
    price: 350,
    badge: "Терміново",
    createdAt: "2025-04-26",
    description: "Ремонт пральних машин, холодильників, дрібної техніки.",
    requirements: "Досвід роботи, власний інструмент.",
    contacts: "Телефон: +380991234574",
    bonus: "Оплата за кожне замовлення.",
  },
  {
    role: "worker",
    title: "Покоївка",
    subtitle: "Прибирання офісу",
    category: "housekeeper",
    location: "Київ, Шевченківський",
    locationKey: "kyiv",
    schedule: "Позмінно",
    scheduleType: "shift",
    employment: "Тимчасова робота",
    employmentType: "temporary",
    frequency: "Щодня",
    frequencyType: "daily",
    price: 200,
    badge: "Перевірено",
    createdAt: "2025-04-25",
    description: "Прибирання офісних приміщень, виніс сміття, миття підлоги.",
    requirements: "Охайність, відповідальність.",
    contacts: "Телефон: +380991234575",
    bonus: "Чайові.",
  },
];
